# Generated by Django 4.2 on 2023-04-11 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='state_name',
        ),
    ]
