# Generated by Django 4.2 on 2023-04-11 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0002_remove_state_state_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='state',
            name='state_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
