# Generated by Django 4.2 on 2023-04-11 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0003_address_state_state_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
