# Generated by Django 4.2 on 2023-04-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0005_address_pin_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='pin_code',
        ),
    ]
