# Generated by Django 4.2 on 2023-04-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0006_remove_address_pin_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pin_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
