# Generated by Django 4.2 on 2023-04-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0007_address_pin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameModel(
            old_name='City_Model',
            new_name='City',
        ),
        migrations.AddField(
            model_name='state',
            name='state_area',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
