# Generated by Django 4.2 on 2023-04-11 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0008_company_rename_city_model_city_state_state_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state_area',
            new_name='state_area_wise',
        ),
        migrations.AddField(
            model_name='city',
            name='city_capital',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
