# Generated by Django 4.2 on 2023-04-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0009_address_model_delete_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=255)),
                ('pin_code', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Address_Model',
        ),
    ]
