# Generated by Django 4.2 on 2023-04-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0010_address_delete_address_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='city_capital',
        ),
        migrations.AddField(
            model_name='company',
            name='comp_location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='country_capital',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
