# Generated by Django 4.2 on 2023-04-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0012_actor_category_customer_film_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Please enter your email address', max_length=255, null=True, unique=True),
        ),
    ]
