# Generated by Django 4.2 on 2023-04-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0013_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, help_text='Please enter your email address', max_length=100, null=True, unique=True),
        ),
    ]
