# Generated by Django 4.2 on 2023-04-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0014_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(blank=True, help_text='Please enter your last name', max_length=250),
        ),
    ]
