# Generated by Django 4.2 on 2023-04-11 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0015_alter_customer_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
