# Generated by Django 4.2 on 2023-04-11 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0016_alter_state_state_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='State',
        ),
        migrations.AlterField(
            model_name='city',
            name='country',
            field=models.ForeignKey(blank=True, help_text='foriegn key relation field', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_city', to='slack_app.country'),
        ),
        migrations.AlterField(
            model_name='filmactor',
            name='actor',
            field=models.OneToOneField(blank=True, help_text='One to one relation field', null=True, on_delete=django.db.models.deletion.CASCADE, to='slack_app.actor'),
        ),
    ]
