# Generated by Django 4.2 on 2023-04-11 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0017_delete_company_delete_state_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_last_update',
            field=models.DateField(),
        ),
    ]
