# Generated by Django 4.2 on 2023-04-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slack_app', '0018_alter_category_category_last_update'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Country',
            new_name='Country_Model',
        ),
        migrations.RenameField(
            model_name='filmactor',
            old_name='actor_film',
            new_name='film_actor',
        ),
        migrations.RemoveField(
            model_name='language',
            name='language_last_update',
        ),
        migrations.AddField(
            model_name='actor',
            name='actor_email',
            field=models.EmailField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='language_last_date',
            field=models.DateField(auto_now=True, help_text='this field in date format will be updated'),
        ),
        migrations.AddField(
            model_name='language',
            name='language_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
